### ISSUE TITLE
Fix: Unión de las distintas partes del alquiler de garajes

### ISSUE THREAD

**Issue by laurolmer** [Aparking/AparKing_Frontend#15]
Se trata de una tarea independiente que surge de la necesidad de juntar las distintas partes que se han hecho entre varios miembros para que todo funcione correctamente y esté ordenado en el tabs.

**Comment by perealberto** [comment]
Me parece bien que lo hayas tenido en cuenta @laurolmer ya que por diversos motivos, estamos atascándonos los diferentes desarrolladores de esta sección ya que nuestras tareas tienen cierto grado de dependencia. ¡Bien visto! 🎯

**Comment by laurolmer** [comment]
Cierro la tarea ya que ya uní en el Frontend la parte del componente de @silvglad y mía.
