### ISSUE TITLE
Fix: Posibilidad de pagar en Efectivo

### ISSUE THREAD

**Issue by ivasansan1** [Aparking/AparKing_Frontend#70]
Arreglar la funcionalidad para poder pagar en efectivo. Actualmente solo se puede pagar con tarjea. Aunque pongas que pagas en efectivo te redirige al pago con tarjeta

Pd: para ver el error ver el video en ?-Dudas-Generales-¬ de Discord

**Comment by CarmenRuizPorcel** [comment]
@ivasansan1 mueve esta issue a Backend, ahí están todas la issues

**Comment by CarmenRuizPorcel** [comment]
He movido la issue al backend
